### ISSUE TITLE
modify partitionStableLastBits

### ISSUE THREAD

**Issue by da0ka** [aldo-gutierrez/bitmasksorterJS#1]
leftX is unnecessary. and possible to reduce iteration(line 118). is it correct?
`function partitionStableLastBits(array, start, end, mask, twoPowerK, aux) {`
`	let count = Array(twoPowerK).fill(0), n=end-start;`
`	for (let i = start; i < end;)`
`		count[array[i++] & mask]++;`
`	for (let i = 0,c,s=0;s<n;s+=c)c=count[i], count[i++]=s;`
`	for (let i = start; i < end;) {`
`		let element = array[i++];`
`		aux[count[element & mask]++] = element;`
`	}`
`	arraycopy(aux, 0, array, start,n);`
`}`
And partitionStableGroupBits:
`function partitionStableGroupBits(array, start, end, mask, shiftRight, twoPowerK, aux) {`
`	let count = Array(twoPowerK).fill(0), n=end-start;`
`	for (let i = start; i < end;)`
`		count[(array[i++] & mask) >> shiftRight]++;`
`	for (let i = 0,c,s=0;s<n;s+=c)c=count[i], count[i++]=s;`
`	for (let i = start; i < end;) {`
`		let element = array[i++];`
`		aux[count[(element & mask) >> shiftRight]++] = element;`
`	}`
`	arraycopy(aux, 0, array, start,n);`
`}`

**Comment by aldo-gutierrez** [comment]
Your code works, I will check it

**Comment by aldo-gutierrez** [comment]
modified and pushed
