### ISSUE TITLE
Uncaught ReferenceError

### ISSUE THREAD

**Issue by da0ka** [aldo-gutierrez/bitmasksorterJS#3]
error in line 156. maybe its code should be `Array(Math.max(n1, n2))`
And I have suggestion in line 137. How about `unsigned=0<new array.constructor([-1])[0]`?

**Comment by aldo-gutierrez** [comment]
- Fixed max to Math.max
- Removed unsigned variable as by default variables in JavaScript are signed Float64 bit numbers
in the future the library will support UInt32Array and UInt64Array

da0ka A new release that supports Float64 and Numbers has been committed, also README.md updated
